---
pipeline:
  validate-template:
    image: robertstettner/drone-cloudformation
    pull: true
    parallel: true
    batch:
      - mode: validate
        template: aws/ecr.yml
      - mode: validate
        template: aws/infrastructure.yml
    when:
      event: push

  notify:
    image: plugins/slack
    webhook: ${SLACK_WEBHOOK}
    channel: dp_bots
    when:
      status:
        - success
        - failure

