---
pipeline:
  validate-template:
    image: robertstettner/drone-cloudformation
    pull: true
    parallel: true
    batch:
      - mode: validate
        template: aws/ecr.yml
    when:
      event: push

  test-ecr:
    image: trinitymirror/drone-cloudformation
    stackname: newdronetest
    template: aws/ecr.yml
    when:
      event: deployment

