---
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - bertha
      - stable
      - prod

Resources:
  ECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: com.reachplc/ecr-test
      'Fn::Transform':
        Name: 'AWS::Include'
        Parameters:
          Location: !Sub s3://uj-cf-snippets-${Environment}/ecr/accessPolicy/default.yml
      'Fn::Transform':
        Name: 'AWS::Include'
        Parameters:
          Location: !Sub s3://uj-cf-snippets-${Environment}/ecr/lifecyclePolicy/default.yml
